//// translations

var Traducoes = {
    "1": "Note created",
    "2": "Edit",
    "3": "OK",
    "4": "Contact card",
    "5": "Location card",
    "6": "Share GPS",
    "7": "You received an AirDrop from",
    "8": "Contact received via AirDrop",
    "9": "Create new chat",
    "10": "Audio",
    "11": "GPS",
    "12": "Contact",
    "13": "New email from",
    "14": "From",
    "15": "Cc/Bcc, From:",
    "16": "Email not found",
    "17": "€",
    "18": "Total",
    "19": "Money in",
    "20": "Money out",
    "21": "Transferred to",
    "22": "in the amount of",
    "23": "You received a transfer from",
    "24": "Hello",
    "25": "Favorite ads",
    "26": "New ad posted",
    "27": "New ad posted by",
    "28": "Photo card",
    "29": "Share photo",
    "30": "Photo",
    "31": "by",
    "32": "Video",
    "33": "Choose Photo",
    "34": "Take Photo",
    "35": "iPhone from",
    "36": "This",
    "37": "Link",
    "38": "Enter old code",
    "39": "Enter new code",
    "40": "Excellent",
    "41": "Sufficient",
    "42": "Degraded",
    "43": "Customized",
    "44": " - Retweeted tweet",
    "45": "New tweet posted by",
    "46": "New tweet posted",
    "47": "Entered in",
    "48": "Following",
    "49": "Followers",
    "50": "Tell this user to change their description!",
    "51": "Following",
    "52": "Follow",
    "53": "New follow from",
    "54": "New follow received",
    "55": "Not following",
    "56": "New reply from",
    "57": "New reply received",
    "58": "You were mentioned in a tweet",
    "59": "Day: ",
    "60": "Individual",
    "61": "Amount",
    "62": "New order placed, amount: ",
    "63": "You made a payment of",
    "64": "Recommended for",
    "65": "Music",
    "66": "songs",
    "67": "Good morning",
    "68": "Good afternoon",
    "69": "Good evening",
    "70": "Tier: ",
    "71": "GET",
    "72": "REMOVE",
    "73": "Edit",
    "74": "Cancel",
    "75": "Open gallery",
    "76": "Send Location",
    "77": "participants",
    "78": "Admin",
    "79": "No messages",
    "80": "New message from",
    "81": "likes",
    "82": "New post posted by",
    "83": "New post posted",
    "84": "Delete story",
    "85": "View story",
    "86": "Start live",
    "87": "Contacts",
    "88": "Remove from favorites",
    "89": "Add to favorites",
    "90": "Edit contact",
    "91": "First name",
    "92": "Last name",
    "93": "IBAN",
    "94": "Company",
    "95": "phone number",
    "96": "OK",
    "97": "Cancel",
    "98": "Add photo",
    "99": "Unknown",
    "100": "New contact",
    "101": "Recents",
    "102": "Create / use chat",
    "103": "Start",
    "104": "Stop",
    "105": "Clear",
    "106": "Save",
    "107": "Resume",
    "108": "Pause",
    "109": "New message from",
    "110": "New AirDrop from",
    "111": "Alarm",
    "112": "triggered",
    "113": "calling: mobile...",
    "114": "Stop Alarm",
    "115": "Select Country or Region",
    "116": "More Countries or Regions",
    "117": "Portugal",
    "118": "United States",
    "119": "Continue",
    "120": "Welcome to Phone System",
    "121": "Time",
    "123": "Unknown",
    "124": "Details",
    "125": "License plate",
    "126": "Status",
    "127": "Saved",
    "128": "Seized",
    "129": "Out",
    "130": "Location",
    "131": "City services",
    "132": "Personal contacts",
    "133": "Current job",
    "134": "Current grade",
    "135": "phone",
    "136": "Wallet",
    "137": "Logout",
    "138": "Change password",
}

/// months

var meses = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
];

// days of week

var dias = [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday',
]